### PR TITLE
UI & Registration

### PR DESCRIPTION
**Pull request by jmalkurdi42**
- Login/Logout feature
- Custom fonts
- Basic UI elements
- Account creation
- Autofill username and password based off of saved account information

### CODE REVIEW

**Comment by Jscott7227** [comment]
Screenshot_20240912_160327
When clicking to enter text on phone the keyboard drags some element off the screen and creates this warning. If you could fix this that would be great. Also we may want to remove sales page because I believe it is currently out of scope

**Comment by jmalkurdi42** [comment]
> Screenshot_20240912_160327 When clicking to enter text on phone the keyboard drags some element of the screen and creates this warning. If you could fix this that would be great. Also we may want to remove sales page because I believe it is currently out of scope

Ah, my bad. I've been only debugging using the vscode emulator. I'll fix it ASAP. I'll also remove the sales page when I get done fixing the error. I'm guessing you were able to create an account and sign in though right?

**Comment by Jscott7227** [comment]
> > Screenshot_20240912_160327 When clicking to enter text on phone the keyboard drags some element of the screen and creates this warning. If you could fix this that would be great. Also we may want to remove sales page because I believe it is currently out of scope
> 
> Ah, my bad. I've been only debugging using the vscode emulator. I'll fix it ASAP. I'll also remove the sales page when I get done fixing the error. I'm guessing you were able to create an account and sign in though right?

Sorry just saw this. Yes both the login and account creation worked. Ideally I would like to get this merged into dev before class  Monday so that we can divvy out some more work to do before the demo Thursday.

**Comment by Swolford0408** [comment]
> > > Screenshot_20240912_160327 When clicking to enter text on phone the keyboard drags some element of the screen and creates this warning. If you could fix this that would be great. Also we may want to remove sales page because I believe it is currently out of scope
> > 
> > 
> > Ah, my bad. I've been only debugging using the vscode emulator. I'll fix it ASAP. I'll also remove the sales page when I get done fixing the error. I'm guessing you were able to create an account and sign in though right?
> 
> Sorry just saw this. Yes both the login and account creation worked. Ideally I would like to get this merged into dev before class Monday so that we can divvy out some more work to do before the demo Thursday.

Any word on it being fixed because I can approve the pull if so?

**Comment by jmalkurdi42** [comment]
> > > > Screenshot_20240912_160327 When clicking to enter text on phone the keyboard drags some element of the screen and creates this warning. If you could fix this that would be great. Also we may want to remove sales page because I believe it is currently out of scope
> > > 
> > > 
> > > Ah, my bad. I've been only debugging using the vscode emulator. I'll fix it ASAP. I'll also remove the sales page when I get done fixing the error. I'm guessing you were able to create an account and sign in though right?
> > 
> > 
> > Sorry just saw this. Yes both the login and account creation worked. Ideally I would like to get this merged into dev before class Monday so that we can divvy out some more work to do before the demo Thursday.
> 
> Any word on it being fixed because I can approve the pull if so?

I wasn't able to replicate the bug exactly, but I wrapped everything with SafeArea and SingeChildScrollView. That should allow scrolling when the UI doesn't exactly fit your device.

**Review by Jscott7227 — APPROVED** [review]
Looks good probably will have to change the dynamic name code when we get the API integrated but everything else is good.

**Pull request merged**
